#!/bin/ksh


function convertReturnValue
{
   typeset rtnVal=$1
   if [[ -z $AMS_RESULTS_DIR ]]
   then
       typeset AMS_RESULTS_DIR="../psf"
   fi
   typeset logFileName="${AMS_RESULTS_DIR}/logFile"
   if [[ "$1" = 1 && -s "$logFileName" ]]
   then
       rtnVal=$2
   fi
   # Supply the value back to the caller.
   return $rtnVal
}

# Set location variables

if [[ -z $AMS_CIC_HIER ]]; then
   export    AMS_CIC_HIER=/users/soft/opus/Linux/IC6.1.8
fi

if [[ -z $AMS_IUS_HIER ]]; then
   export    AMS_IUS_HIER=/users/soft/opus/Linux/INCISIVE-15.20.074
fi

if [[ -z $IC_INVOKE_DIR ]]; then
   export    IC_INVOKE_DIR=/users/cao/galayko/cadence_amsC35_projEACN
fi

export UNIFIED_DB_STITCHING_DISABLE=1

export TESTBENCH_TOPCELL="ADC_SAR"
irun -f irunArgs 


convertReturnValue $? 0

